### ISSUE TITLE
Concretar versión de Python entre los miembros del equipo.

### ISSUE THREAD

**Issue by Patacabra** [Sputnikomk2/ProyectoSputniko#36]
#HU1

**Comment by JJ** [comment]
Este es el tipo de cosas que, como no van directamente (sino indirectamente) a satisfacer una necesidad del cliente, perfectamente pueden no enlazar una historia de usuario o simplemente decidirlo en el canal de Telegram o en la daily.  Como no es algo que vaya a suponer un cambio en el código ni en el repositorio, es mejor no ponerlo como issue, porque todo issue se tiene que cerrar con un cambio en el repositorio (usando la orden `closes #issue`)

**Comment by Patacabra** [comment]
Entendido! 👍

**Comment by JJ** [comment]
Como ya os he dicho, van a saltar todo tipo de errores si no cerráis desde un commit. Lo mejor es que borréis el issue en este caso.
