### ISSUE TITLE
¿Cuáles son los objetivos?

### ISSUE THREAD

**Issue by Carmenalbl** [Sputnikomk2/ProyectoSputniko#40]
Necesitamos delimitar cuales son los objetivos principales entre los que vamos a movernos. 

#53

**Comment by Carmenalbl** [comment]
Tenemos dos objetivos principales.
Objetivo 1: Que estén motivados mediante incentivos.
Objetivo 2: Que a parte de mantenerse motivados aprendan sobre el medio ambiente mientras juegan. 
-- Considerando que estos dos objetivos son el fin último de nuestro juego.

**Comment by JJ** [comment]
Enlaza por favor el PR al que se refiera este issue.

**Comment by JJ** [comment]
Sólo tenéis este issue asignado; en la *daily* deberíais haberos repartido el trabajo y cada uno debería tener un issue asignado. Si no es así, es imposible que sepáis en qué estáis trabajando cada uno.
