### ISSUE TITLE
Definir las entidades y atributos del problema

### ISSUE THREAD

**Issue by Franjapeji** [Sputnikomk2/ProyectoSputniko#65]
PR #66 
Entidad y atributos de modelo.

**Comment by JJ** [comment]
Todos los issues deben ir asignados a un PR, y *todos* se solucionan con código. Lo que estás poniendo aquí aparentemente reproduce lo que debería hacerse para este milestone. DDD en particular, es una herramienta para llevar el dominio del problema (descrito en las historias de usuario) a código.

**Comment by JJ** [comment]
En general, también, deberíais crear, asignar y trabajar en los issues en equipo; crear un issue y resolverlo no parece que aporte mucho al cliente, ¿no crees?

**Comment by Franjapeji** [comment]
Alumno  | Id
Pregunta | Dificultad, categoría, enunciado, respuesta correcta
Respuesta | Enunciado, es_correcta
Partida  | Duración, puntuación, preguntas_respondidas
Premio   | Descripción, puntos_necesarios

**Comment by JJ** [comment]
Por otro lado, está bien que trabajéis autónomamente y eso es lo que se busca, pero ya he comentado que no podéis autoasignaros un issue, y menos un issue que *no representa un problema*, y cuyo título no tiene nada que ver con el código que se ha creado (aunque este código no lo enlaza).
En informática lo que importa no es el resultado final, es el proceso. Si no se siguen las buenas prácticas en el proceso de diseño y creación del código, no se está aprovechando el tiempo del equipo ni añadiendo valor al cliente.

**Comment by Franjapeji** [comment]
Vale, no me autoasignaré en el siguiente issue.
